rating:
  service:
    port: 8050
    image:
      name: cr.yandex/crpg934f0qu6v6sq6pj9//rating
      version: latest
    database:
      name: rating
library:
  service:
    port: 8060
    image:
      name: cr.yandex/crpg934f0qu6v6sq6pj9//library
      version: latest
    database:
      name: library
reservation:
  service:
    port: 8070
    image:
      name: cr.yandex/crpg934f0qu6v6sq6pj9//reservation
      version: latest
    database:
      name: reservation
gateway:
  service:
    port: 8080
    image:
      name: cr.yandex/crpg934f0qu6v6sq6pj9//gateway
      version: latest
    isGateway: true
