name: GitHub Classroom Workflow
on:
  push:
    branches:
      - master

env:
  DOCKERHUB_PASS: Wi@REtCTC5maj9z
  DOCKERHUB_USERNAME: krutoypan3
  K8S_TOKEN: ${{ secrets.K8S_TOKEN }}
  K8S_URL: ${{ secrets.K8S_URL }}

jobs:
  build:
    name: Autograding
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: '8'
          distribution: 'adopt'


      - uses: docker/setup-buildx-action@v2
      - name: Build images
        run: docker-compose build -t iisus

      - name: Build, publish to docker hub
        run: |
         echo "$DOCKERHUB_PASS" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin
         docker build --no-cache -t krutoypan3/gateway ./src/gateway/ && docker push krutoypan3/gateway:latest
         docker build --no-cache -t krutoypan3/rating ./src/rating/ && docker push krutoypan3/rating:latest
         docker build --no-cache -t krutoypan3/library ./src/library/ && docker push krutoypan3/library:latest
         docker build --no-cache -t krutoypan3/reservation ./src/reservation/ && docker push krutoypan3/reservation:latest


      - name: k8s deploy
        run: |
          kubectl config set-cluster lab4rsoiclaster --server="$K8S_URL" --insecure-skip-tls-verify=true
          kubectl config set-credentials admin --token="$K8S_TOKEN"
          kubectl config set-context default --cluster=lab4rsoiclaster --user=admin
          kubectl config use-context default
          kubectl apply -f k8s.yml
          





      - name: Run API Tests
        uses: matt-ball/newman-action@master
        with:
          collection: v4/postman/collection.json
          environment: v4/postman/environment.json
          delayRequest: 100
          reporters: '[ "cli" ]'

      - uses: education/autograding@v1
        id: autograder
        continue-on-error: true

      - name: Github auto grader mark
        uses: Romanow/google-sheet-autograder-marker@v1.0
        with:
          google_token: ${{secrets.GOOGLE_API_KEY}}
          sheet_id: "1xkgjUX6Qmk7rdJG-QPOToav-HWWtthJjnShIKnw3oIY"
          homework_number: 4
          user_column: 'D'
          column_offset: 'F'
          mark: "'+"