name: GitHub Classroom Workflow
on:
  push:
    branches:
      - master

env:
  DOCKERHUB_PASS: Wi@REtCTC5maj9z
  DOCKERHUB_USERNAME: krutoypan3
  KUBE_HOST: https://51.250.66.197
  KUBE_TOKEN: ZXlKaGJHY2lPaUpTVXpJMU5pSXNJbXRwWkNJNkltSnZSMjQxZVdaaVZuYzBNbDlCYXpKb1IwRlhSbE5WYkMxaE5GUjBlbWxCZVY5aE1FSmpNREZMVldNaWZRLmV5SnBjM01pT2lKcmRXSmxjbTVsZEdWekwzTmxjblpwWTJWaFkyTnZkVzUwSWl3aWEzVmlaWEp1WlhSbGN5NXBieTl6WlhKMmFXTmxZV05qYjNWdWRDOXVZVzFsYzNCaFkyVWlPaUpyZFdKbExYTjVjM1JsYlNJc0ltdDFZbVZ5Ym1WMFpYTXVhVzh2YzJWeWRtbGpaV0ZqWTI5MWJuUXZjMlZqY21WMExtNWhiV1VpT2lKbmFYUnNZV0l0WVdSdGFXNHRkRzlyWlc0dGRtZHFaR1FpTENKcmRXSmxjbTVsZEdWekxtbHZMM05sY25acFkyVmhZMk52ZFc1MEwzTmxjblpwWTJVdFlXTmpiM1Z1ZEM1dVlXMWxJam9pWjJsMGJHRmlMV0ZrYldsdUlpd2lhM1ZpWlhKdVpYUmxjeTVwYnk5elpYSjJhV05sWVdOamIzVnVkQzl6WlhKMmFXTmxMV0ZqWTI5MWJuUXVkV2xrSWpvaU1UQmpZVEZrWmpjdE1EQXdaUzAwTXpJd0xUZ3pNVFl0TXpReFpHVmxaV000Tmpoaklpd2ljM1ZpSWpvaWMzbHpkR1Z0T25ObGNuWnBZMlZoWTJOdmRXNTBPbXQxWW1VdGMzbHpkR1Z0T21kcGRHeGhZaTFoWkcxcGJpSjkuakdKVXFoOGs4eVAyd2pfb0o1aGNITkVFWWw4QmVCX0xaMFBMZ0xrdGhyZU9Ea2dhSkRSVER0VFVKYTZHYWd3dXhLZ2I3ejltaDBLWU9zenlaaXZYSFNDazR3a2p3Y1VKZmw4QmE2dk4wNXJ0OU1VcXRlWEx4WkJHYlJBR3d0YWtEbTRWTHhFSGVHZXhNSDBRZG5Ybkhra0tyR25NZTNjMTBIT3RZMFJySFZRZ0FRWm9CRHR4OHM4ZkNZWFJWVzByUVprUm5lMDM1MXA1SW96SGNHRENwaFM3NG9icXhidDR5TU4zN0hRWmNCemRHOWQzbkpyUGNaOEo3WGxzdThlQmVtQ0IzNVJPMG9GRkVFNlN5RnlXQUZ4QjNiVF83eHZ6cklRSzlvUE1DSmtGWWNvRE5ReFlHMjQwQ1VlZXdPemtrekxtcF9rOFVHRzVmYjBXWVNkcVV3

jobs:
  build:
    name: Autograding
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: '8'
          distribution: 'adopt'


      - uses: docker/setup-buildx-action@v2
      - name: Build images
        run: docker-compose build -t iisus

      - name: Login container registry
        id: login-cr
        uses: yc-actions/yc-cr-login@v1
        with:
          yc-sa-json-credentials: ${{ secrets.YA__JSON_SERVICE_ACCOUNT }}

      - name: Build, publish to docker hub yc
        run: |
         echo "$DOCKERHUB_PASS" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin
#         docker build --no-cache -t cr.yandex/crpg934f0qu6v6sq6pj9/gateway ./src/gateway/ && docker push cr.yandex/crpg934f0qu6v6sq6pj9/gateway:latest
#         docker build --no-cache -t cr.yandex/crpg934f0qu6v6sq6pj9/rating ./src/rating/ && docker push cr.yandex/crpg934f0qu6v6sq6pj9/rating:latest
#         docker build --no-cache -t cr.yandex/crpg934f0qu6v6sq6pj9/library ./src/library/ && docker push cr.yandex/crpg934f0qu6v6sq6pj9/library:latest
#         docker build --no-cache -t cr.yandex/crpg934f0qu6v6sq6pj9/reservation ./src/reservation/ && docker push cr.yandex/crpg934f0qu6v6sq6pj9/reservation:latest


      - name: Kubernetes
        run: |
          echo "run deploy"
          kubectl config set-cluster yc-lab4rsoiclaster --server="$KUBE_HOST" --insecure-skip-tls-verify=true
          kubectl config set-credentials gitlab-admin --token="$KUBE_TOKEN"
          kubectl config set-context default --cluster=yc-lab4rsoiclaster --user=gitlab-admin
          kubectl config use-context default
          
          kubectl config view --raw
          
          helm install services k8s/services-chart/

          sleep 45



      - name: Run API Tests
        uses: matt-ball/newman-action@master
        with:
          collection: v4/postman/collection.json
          environment: v4/postman/environment.json
          delayRequest: 100
          reporters: '[ "cli" ]'

      - uses: education/autograding@v1
        id: autograder
        continue-on-error: true

      - name: Github auto grader mark
        uses: Romanow/google-sheet-autograder-marker@v1.0
        with:
          google_token: ${{secrets.GOOGLE_API_KEY}}
          sheet_id: "1xkgjUX6Qmk7rdJG-QPOToav-HWWtthJjnShIKnw3oIY"
          homework_number: 4
          user_column: 'D'
          column_offset: 'F'
          mark: "'+"