name: GitHub Classroom Workflow
on:
  push:
    branches:
      - master

env:
  DOCKERHUB_PASS: Wi@REtCTC5maj9z
  DOCKERHUB_USERNAME: krutoypan3
  K8S_TOKEN: eyJhbGciOiJSUzI1NiIsImtpZCI6ImJvR241eWZiVnc0Ml9BazJoR0FXRlNVbC1hNFR0emlBeV9hMEJjMDFLVWMifQ.eyJpc3MiOiJrdWJlcm5ldGVzL3NlcnZpY2VhY2NvdW50Iiwia3ViZXJuZXRlcy5pby9zZXJ2aWNlYWNjb3VudC9uYW1lc3BhY2UiOiJrdWJlLXN5c3RlbSIsImt1YmVybmV0ZXMuaW8vc2VydmljZWFjY291bnQvc2VjcmV0Lm5hbWUiOiJpbS1ub3QtbGlrZS1oYXJkLWVkdWNhdGlvbi10b2tlbi0ybGNoNyIsImt1YmVybmV0ZXMuaW8vc2VydmljZWFjY291bnQvc2VydmljZS1hY2NvdW50Lm5hbWUiOiJpbS1ub3QtbGlrZS1oYXJkLWVkdWNhdGlvbiIsImt1YmVybmV0ZXMuaW8vc2VydmljZWFjY291bnQvc2VydmljZS1hY2NvdW50LnVpZCI6ImZjNGE5Yjc2LTM3NWUtNGZjZi1hNDFiLWNkMzZhZWE0N2Q2NiIsInN1YiI6InN5c3RlbTpzZXJ2aWNlYWNjb3VudDprdWJlLXN5c3RlbTppbS1ub3QtbGlrZS1oYXJkLWVkdWNhdGlvbiJ9.Oaz72hSgIUIsKpfacpX14lg8ESOkxxXygeRiv3fb6vNtHjh2pik4clDDLKATkS4c0TovovK_d3L_Itq1knF0cIurxv2xEJeMOHl2YMcZ29JCJ0UpUtBb__a7ONARYQL3Ykar_z2cS9YoRfv6OGkKgbxHTMLY-eQHu4FVBHEjbjVAThV9Jy8xcy0gJ-BLGKKgg0P4-xucpfWd4VY4dzvQqBlydZgglxHyyN3fY4dvG5S2BdhNu0AbXX0c3vrDI_eOUrhb93dM4Y57VvtRmeyQy2rYhfwZEeOCaN49e4c_eOJCmeZ6KqlbcaMMeRQ6p2eonU7iuPibcBe8IFs8Q7JYHQ
  K8S_URL: 51.250.66.197

jobs:
  build:
    name: Autograding
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: '8'
          distribution: 'adopt'


      - uses: docker/setup-buildx-action@v2
      - name: Build images
        run: docker-compose build -t iisus

      - name: Build, publish to docker hub
        run: |
         echo "$DOCKERHUB_PASS" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin
         docker build --no-cache -t krutoypan3/gateway ./src/gateway/ && docker push krutoypan3/gateway:latest
         docker build --no-cache -t krutoypan3/rating ./src/rating/ && docker push krutoypan3/rating:latest
         docker build --no-cache -t krutoypan3/library ./src/library/ && docker push krutoypan3/library:latest
         docker build --no-cache -t krutoypan3/reservation ./src/reservation/ && docker push krutoypan3/reservation:latest


      - name: k8s deploy
        run: |
          kubectl config set-cluster lab4rsoiclaster --server="$K8S_URL" --insecure-skip-tls-verify=true
          kubectl config set-credentials admin --token="$K8S_TOKEN"
          kubectl config set-context default --cluster=lab4rsoiclaster --user=admin
          kubectl config use-context default
          kubectl apply -f k8s.yml
          





      - name: Run API Tests
        uses: matt-ball/newman-action@master
        with:
          collection: v4/postman/collection.json
          environment: v4/postman/environment.json
          delayRequest: 100
          reporters: '[ "cli" ]'

      - uses: education/autograding@v1
        id: autograder
        continue-on-error: true

      - name: Github auto grader mark
        uses: Romanow/google-sheet-autograder-marker@v1.0
        with:
          google_token: ${{secrets.GOOGLE_API_KEY}}
          sheet_id: "1xkgjUX6Qmk7rdJG-QPOToav-HWWtthJjnShIKnw3oIY"
          homework_number: 4
          user_column: 'D'
          column_offset: 'F'
          mark: "'+"