name: GitHub Classroom Workflow
on:
  push:
    branches:
      - master

env:
  DOCKERHUB_PASS: Wi@REtCTC5maj9z
  DOCKERHUB_USERNAME: krutoypan3
  KUBE_HOST: https://51.250.66.197
  KUBE_TOKEN: YCN2XONnQZdvHrZL2caLb8x2H6JtUFHdBE_8bZj8
  AUTH: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUM1ekNDQWMrZ0F3SUJBZ0lCQURBTkJna3Foa2lHOXcwQkFRc0ZBREFWTVJNd0VRWURWUVFERXdwcmRXSmwKY201bGRHVnpNQjRYRFRJek1ERXdOekV4TWpJMU5sb1hEVE16TURFd05ERXhNakkxTmxvd0ZURVRNQkVHQTFVRQpBeE1LYTNWaVpYSnVaWFJsY3pDQ0FTSXdEUVlKS29aSWh2Y05BUUVCQlFBRGdnRVBBRENDQVFvQ2dnRUJBS3hPClgxQllOV3MxMFN3MGFMWlVVMzhNbllnNk42V3VBRzJqWnF5di8xamFHbFo4T0Y5R3VqTmptNmFBNDZ5SHRDQmQKcjRLYTlkaEFRKzJhNzM5OTZXOG53bjFrK244UmZOTG9GT25jUzJ0aldsbzNPaVk4Q2p2SkFqSEQ5NDRoeElYNwpwZkNGWCtvWnVCYmMzSVh1TUwxbEVDQXh4QkdDL2hyOGNMdDNmamlOUlNGWFVFSWVHbVFQNjVtcWRwK0FWWXFrCllXVVUwOE9WQ2lJUHVVaXkyb01ud3h4RXpEMEFVR0hlbXIwNWRKeDhvRDVmTHp2RFB1KzJBZlp0NEViZER0dGUKN1g1MlhGRmpKaW4zeTRMMHlYdGF3ZGExTWM3Z25CMis1T2Fka241a0Zjc3BndkwydDR3UHRqNTRXbnNjUU93TAptbmFhZUtIZ016MjFuaWRVNmxjQ0F3RUFBYU5DTUVBd0RnWURWUjBQQVFIL0JBUURBZ0trTUE4R0ExVWRFd0VCCi93UUZNQU1CQWY4d0hRWURWUjBPQkJZRUZDb0d3RzVoNFBhYVBGRXNKOUNJYmV2U3Erc1BNQTBHQ1NxR1NJYjMKRFFFQkN3VUFBNElCQVFBenIwMnNsZnBoUzFBY0FZYitOZ1grS0hSL3lpYmM5dlltZmI4cnRwV1BacmN4ZjBRZwpHNEdTNncyeWNWT3RJVlFFTXNhWDVtMVk2d1E5ZjYrTk9iYUJOOGRob2RxSUsreHAvdGczWlFkWEJhbElnZDFHCkdmd0NOd2h2SWQ3NnFKci8vbmlqcGhRdmNZOC9VdDl2elVEdVhVYlIzNUVlWngxVTk4REVlOHFhUTc2R3JDQm8KdStqcTVEaTV2Yjlucng5RDFoUlBWaXNta1VqcCs4ODZBQ2VLdEFFeWxRaFFkR2RRdlNyNm1uTTZXa29GWUp4MwplbFBXUDE5VGJVN3ZZWWp6OGZRdUVkaEhHV1pVNVIxUUhvNXozaGVlMDFrQklKSzhVM1ZEM1EzNzJPQStLQjQ2Ck5vVXU0REthSysyZEQ3cWhNaDh4WGw3UHNibmdOWC91Mk9ZVgotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCg==

jobs:
  build:
    name: Autograding
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: '8'
          distribution: 'adopt'


      - uses: docker/setup-buildx-action@v2
      - name: Build images
        run: docker-compose build -t iisus

      - name: Login container registry
        id: login-cr
        uses: yc-actions/yc-cr-login@v1
        with:
          yc-sa-json-credentials: ${{ secrets.YA__JSON_SERVICE_ACCOUNT }}

      - name: Build, publish to docker hub yc
        run: |
         echo "$DOCKERHUB_PASS" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin
         docker build --no-cache -t cr.yandex/crpg934f0qu6v6sq6pj9/gateway ./src/gateway/ && docker push cr.yandex/crpg934f0qu6v6sq6pj9/gateway:latest
         docker build --no-cache -t cr.yandex/crpg934f0qu6v6sq6pj9/rating ./src/rating/ && docker push cr.yandex/crpg934f0qu6v6sq6pj9/rating:latest
         docker build --no-cache -t cr.yandex/crpg934f0qu6v6sq6pj9/library ./src/library/ && docker push cr.yandex/crpg934f0qu6v6sq6pj9/library:latest
         docker build --no-cache -t cr.yandex/crpg934f0qu6v6sq6pj9/reservation ./src/reservation/ && docker push cr.yandex/crpg934f0qu6v6sq6pj9/reservation:latest


      - name: Configure kubectl
        run: |
          mkdir $HOME/.kube
          cp k8s/config.yaml $HOME/.kube/config

      - name: Kubernetes
        run: |
          echo "run deploy"
          
          kubectl config view --raw
          
          helm uninstall services
          helm install services k8s/services-chart/

          sleep 45



      - name: Run API Tests
        uses: matt-ball/newman-action@master
        with:
          collection: v4/postman/collection.json
          environment: v4/postman/environment.json
          delayRequest: 100
          reporters: '[ "cli" ]'

      - uses: education/autograding@v1
        id: autograder
        continue-on-error: true

      - name: Github auto grader mark
        uses: Romanow/google-sheet-autograder-marker@v1.0
        with:
          google_token: ${{secrets.GOOGLE_API_KEY}}
          sheet_id: "1xkgjUX6Qmk7rdJG-QPOToav-HWWtthJjnShIKnw3oIY"
          homework_number: 4
          user_column: 'D'
          column_offset: 'F'
          mark: "'+"