name: GitHub Classroom Workflow
on:
  push:
    branches:
      - master

env:
  DOCKERHUB_PASS: Wi@REtCTC5maj9z
  DOCKERHUB_USERNAME: krutoypan3

jobs:
  build:
    name: Autograding
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: '8'
          distribution: 'adopt'


      - uses: docker/setup-buildx-action@v2
      - name: Build images
        run: docker-compose build -t iisus

      - name: Download YC CLI
        run: |
         curl -sSL https://storage.yandexcloud.net/yandexcloud-yc/install.sh | bash
         source "/home/runner/.bashrc"

      - name: Add YC to bash
        run: |
         export PATH="$PATH:/home/runner/yandex-cloud/completion.zsh.inc"
          
         exec -l $SHELL
         echo 'source /home/runner/yandex-cloud/completion.zsh.inc' >>  ~/.zshrc

      - name: Init YC
        run: |
         yc init


      - name: Build, publish to docker hub yc
        run: |
         echo "$DOCKERHUB_PASS" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin
         docker build --no-cache -t cr.yandex/crpg934f0qu6v6sq6pj9/gateway ./src/gateway/ && docker push cr.yandex/crpg934f0qu6v6sq6pj9/gateway:latest
         docker build --no-cache -t cr.yandex/crpg934f0qu6v6sq6pj9/rating ./src/rating/ && docker push cr.yandex/crpg934f0qu6v6sq6pj9/rating:latest
         docker build --no-cache -t cr.yandex/crpg934f0qu6v6sq6pj9/library ./src/library/ && docker push cr.yandex/crpg934f0qu6v6sq6pj9/library:latest
         docker build --no-cache -t cr.yandex/crpg934f0qu6v6sq6pj9/reservation ./src/reservation/ && docker cr.yandex/crpg934f0qu6v6sq6pj9/reservation:latest


      - name: Install Kubectl
        uses: Azure/setup-kubectl@v3.1

      - name: Create .kube folder
        run: mkdir $HOME/.kube

      - name: Send YC config to K8S
        run: cp ./k8s/config $HOME/.kube/config

      - name: Delete old Service pods
        run: helm delete services

      - name: Delete old Database pods
        run: helm delete databases

      - name: Deploy DB to YC
        run: helm install databases k8s/postgres-chart

      - name: Deploy Services to YC
        run: helm install services k8s/services-chart

      - name: Wait 90 seconds
        run: sleep 90
          





      - name: Run API Tests
        uses: matt-ball/newman-action@master
        with:
          collection: v4/postman/collection.json
          environment: v4/postman/environment.json
          delayRequest: 100
          reporters: '[ "cli" ]'

      - uses: education/autograding@v1
        id: autograder
        continue-on-error: true

      - name: Github auto grader mark
        uses: Romanow/google-sheet-autograder-marker@v1.0
        with:
          google_token: ${{secrets.GOOGLE_API_KEY}}
          sheet_id: "1xkgjUX6Qmk7rdJG-QPOToav-HWWtthJjnShIKnw3oIY"
          homework_number: 4
          user_column: 'D'
          column_offset: 'F'
          mark: "'+"