name: GitHub Classroom Workflow
on:
  push:
    branches:
      - master

env:
  PASSWORD: ${{secrets.PASSWORD}}
  USERNAME: ${{secrets.USERNAME}}
  KUBE_CONFIG: ${{secrets.CONFIG}}
  TOKEN: ${{secrets.TOKEN}}

jobs:
  build:
    name: Autograding
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: '8'
          distribution: 'adopt'


      - uses: docker/setup-buildx-action@v2
      - name: Build images
        run: docker-compose build -t allahpomogi

      - name: Push images
        run: |
          docker login -u krutoypan3 -p Wi@REtCTC5maj9z
          docker tag iisus krutoypan3/allahpomogi
          docker-compose push krutoypan3/allahpomogi:iisus

      - name: deploy
        run: |
          export kubeconfig=$KUBE_CONFIG
          echo $kubeconfig | base64 -d > /tmp/k8s-config
          helm upgrade --install ${GITHUB_REF##*/} --kubeconfig /tmp/k8s-config --namespace=$NAMESPACE ./cicd/library-system
          sleep 120

      - name: Run API Tests
        uses: matt-ball/newman-action@master
        with:
          collection: v4/postman/collection.json
          environment: v4/postman/environment.json
          delayRequest: 100
          reporters: '[ "cli" ]'

      - uses: education/autograding@v1
        id: autograder
        continue-on-error: true

      - name: Github auto grader mark
        uses: Romanow/google-sheet-autograder-marker@v1.0
        with:
          google_token: ${{secrets.GOOGLE_API_KEY}}
          sheet_id: "1xkgjUX6Qmk7rdJG-QPOToav-HWWtthJjnShIKnw3oIY"
          homework_number: 4
          user_column: 'D'
          column_offset: 'F'
          mark: "'+"